Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM3.Data;
using CRM3.Models;
using Microsoft.AspNetCore.Authorization;

namespace CRM3.Controllers
{
    [Authorize]
    public class CompaniesController : Controller
    {
        private readonly CompanyContext _context;

        public CompaniesController(CompanyContext context)
        {
            _context = context;
        }

        // GET: Companies
        [HttpGet]
        public async Task<IActionResult> Index(string id)
        {
            var companies = from c in _context.CompanyDetails
                         select c;

            if (!String.IsNullOrEmpty(id))
            {
                companies = companies.Where(s => s.CompanyName.Contains(id) || s.GroupName.Contains(id));
            }

            return View(await companies.ToListAsync());
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyDetails = await _context.CompanyDetails
                .FirstOrDefaultAsync(m => m.CompanyName == id);
            if (companyDetails == null)
            {
                return NotFound();
            }

            return View(companyDetails);
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompanyName,PublicEmail,ContactPersonOne,PersonalEmailOne,ContactPersonTwo,PersonalEmailTwo,DateCreated,GroupName,Comments,AccountManager")] CompanyDetails companyDetails)
        {
            if (ModelState.IsValid)
            {
                _context.Add(companyDetails);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(companyDetails);
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyDetails = await _context.CompanyDetails.FindAsync(id);
            if (companyDetails == null)
            {
                return NotFound();
            }
            return View(companyDetails);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("CompanyName,PublicEmail,ContactPersonOne,PersonalEmailOne,ContactPersonTwo,PersonalEmailTwo,DateCreated,GroupName,Comments,AccountManager")] CompanyDetails companyDetails)
        {
            if (id != companyDetails.CompanyName)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(companyDetails);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyDetailsExists(companyDetails.CompanyName))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(companyDetails);
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var companyDetails = await _context.CompanyDetails
                .FirstOrDefaultAsync(m => m.CompanyName == id);
            if (companyDetails == null)
            {
                return NotFound();
            }

            return View(companyDetails);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var companyDetails = await _context.CompanyDetails.FindAsync(id);
            _context.CompanyDetails.Remove(companyDetails);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyDetailsExists(string id)
        {
            return _context.CompanyDetails.Any(e => e.CompanyName == id);
        }
    }
}

Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CRM3.Data;
using CRM3.Models;
using Microsoft.AspNetCore.Authorization;

namespace CRM3.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly DashboardContext _context;

        public DashboardController(DashboardContext context)
        {
            _context = context;
        }

        // GET: Dashboard
        public async Task<IActionResult> Index(string sortOrder, string searchString)
        {
            ViewData["StartTimeSortParm"] = String.IsNullOrEmpty(sortOrder) ? "starttime_desc" : "";
            ViewData["DeadlineSortParm"] = sortOrder == "Deadline" ? "deadline_desc" : "Deadline";
            ViewData["CurrentFilter"] = searchString;

            var tasks = from t in _context.Tasks
                        select t;

            if (!String.IsNullOrEmpty(searchString))
            {
                tasks = tasks.Where(t => t.TaskName.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "starttime_desc":
                    tasks = tasks.OrderByDescending(t => t.StartTime);
                    break;
                case "Deadline":
                    tasks = tasks.OrderBy(t => t.Deadline);
                    break;
                case "deadline_desc":
                    tasks = tasks.OrderByDescending(t => t.Deadline);
                    break;
                default:
                    tasks = tasks.OrderBy(t => t.StartTime);
                    break;
            }
            return View(await tasks.AsNoTracking().ToListAsync());
                }

        // GET: Dashboard/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasks = await _context.Tasks
                .FirstOrDefaultAsync(m => m.TaskName == id);
            if (tasks == null)
            {
                return NotFound();
            }

            return View(tasks);
        }
  
        public async Task<ActionResult> _ViewTasks()  
        {  
            return PartialView(await _context.Tasks.ToListAsync());  
        } 

        // GET: Dashboard/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dashboard/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TaskName,StartTime,Deadline,Important,HighComplexity")] Tasks tasks)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tasks);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tasks);
        }

        // GET: Dashboard/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasks = await _context.Tasks.FindAsync(id);
            if (tasks == null)
            {
                return NotFound();
            }
            return View(tasks);
        }

        // POST: Dashboard/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("TaskName,StartTime,Deadline,Important,HighComplexity")] Tasks tasks)
        {
            if (id != tasks.TaskName)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tasks);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TasksExists(tasks.TaskName))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tasks);
        }

        // GET: Dashboard/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tasks = await _context.Tasks
                .FirstOrDefaultAsync(m => m.TaskName == id);
            if (tasks == null)
            {
                return NotFound();
            }

            return View(tasks);
        }

        // POST: Dashboard/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var tasks = await _context.Tasks.FindAsync(id);
            _context.Tasks.Remove(tasks);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TasksExists(string id)
        {
            return _context.Tasks.Any(e => e.TaskName == id);
        }
    }
}

Views/Companies/Create.cshtml
@model CRM3.Models.CompanyDetails

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CompanyDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CompanyName" class="control-label"></label>
                <input asp-for="CompanyName" class="form-control" />
                <span asp-validation-for="CompanyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PublicEmail" class="control-label"></label>
                <input asp-for="PublicEmail" class="form-control" />
                <span asp-validation-for="PublicEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactPersonOne" class="control-label"></label>
                <input asp-for="ContactPersonOne" class="form-control" />
                <span asp-validation-for="ContactPersonOne" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonalEmailOne" class="control-label"></label>
                <input asp-for="PersonalEmailOne" class="form-control" />
                <span asp-validation-for="PersonalEmailOne" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactPersonTwo" class="control-label"></label>
                <input asp-for="ContactPersonTwo" class="form-control" />
                <span asp-validation-for="ContactPersonTwo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonalEmailTwo" class="control-label"></label>
                <input asp-for="PersonalEmailTwo" class="form-control" />
                <span asp-validation-for="PersonalEmailTwo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupName" class="control-label"></label>
                <input asp-for="GroupName" class="form-control" />
                <span asp-validation-for="GroupName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <input asp-for="Comments" class="form-control" />
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccountManager" class="control-label"></label>
                <input asp-for="AccountManager" class="form-control" />
                <span asp-validation-for="AccountManager" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Companies/Delete.cshtml
@model CRM3.Models.CompanyDetails

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CompanyDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublicEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublicEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactPersonOne)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactPersonOne)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonalEmailOne)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonalEmailOne)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactPersonTwo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactPersonTwo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonalEmailTwo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonalEmailTwo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GroupName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comments)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountManager)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountManager)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CompanyName" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Companies/Details.cshtml
@model CRM3.Models.CompanyDetails

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>CompanyDetails</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PublicEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PublicEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactPersonOne)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactPersonOne)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonalEmailOne)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonalEmailOne)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ContactPersonTwo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ContactPersonTwo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PersonalEmailTwo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PersonalEmailTwo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateCreated)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GroupName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GroupName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comments)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comments)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AccountManager)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AccountManager)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CompanyName">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Companies/Edit.cshtml
@model CRM3.Models.CompanyDetails

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CompanyDetails</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CompanyName" />
            <div class="form-group">
                <label asp-for="PublicEmail" class="control-label"></label>
                <input asp-for="PublicEmail" class="form-control" />
                <span asp-validation-for="PublicEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactPersonOne" class="control-label"></label>
                <input asp-for="ContactPersonOne" class="form-control" />
                <span asp-validation-for="ContactPersonOne" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonalEmailOne" class="control-label"></label>
                <input asp-for="PersonalEmailOne" class="form-control" />
                <span asp-validation-for="PersonalEmailOne" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactPersonTwo" class="control-label"></label>
                <input asp-for="ContactPersonTwo" class="form-control" />
                <span asp-validation-for="ContactPersonTwo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonalEmailTwo" class="control-label"></label>
                <input asp-for="PersonalEmailTwo" class="form-control" />
                <span asp-validation-for="PersonalEmailTwo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateCreated" class="control-label"></label>
                <input asp-for="DateCreated" class="form-control" />
                <span asp-validation-for="DateCreated" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GroupName" class="control-label"></label>
                <input asp-for="GroupName" class="form-control" />
                <span asp-validation-for="GroupName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comments" class="control-label"></label>
                <input asp-for="Comments" class="form-control" />
                <span asp-validation-for="Comments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AccountManager" class="control-label"></label>
                <input asp-for="AccountManager" class="form-control" />
                <span asp-validation-for="AccountManager" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Companies/Index.cshtml
@model IEnumerable<CRM3.Models.CompanyDetails>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <ul>
        <li>
            <a asp-action="Create">Add Company</a>
        </li>
        <li>
            <a href="/dashboard/index">View Dashboard</a>
        </li>
    </ul>
</p>
<p>
    <form asp-controller="Companies" asp-action="Index" method="get">
        <p>
            Company or Group Name:<input type="text" name="id" style="margin-left:10px;" />
            <input type="submit" value="Search" />
            <a style="margin-left:10px;" asp-action="Index">View All</a>
        </p>
    </form>
</p>


@foreach (var item in Model) {
    <div>
        <button style="margin:1px;" type="button" class="collapsible">@Html.DisplayFor(model => item.CompanyName)</button>
        <div class="content">
            <h5 class="mb-0">
                <table class="table">
                    <thead>
                        <tr>
                            <th style="width:20%;">
                                @Html.DisplayNameFor(model => model.PublicEmail)
                            </th>
                            <th style="width:20%;">
                                @Html.DisplayNameFor(model => model.ContactPersonOne)
                            </th>
                            <th style="width:20%;">
                                @Html.DisplayNameFor(model => model.PersonalEmailOne)
                            </th>
                            <th style="width:20%;">
                                @Html.DisplayNameFor(model => model.ContactPersonTwo)
                            </th>
                            <th style="width:20%;">
                                @Html.DisplayNameFor(model => model.PersonalEmailTwo)
                            </th>
                        </tr>
                    </thead>
                    <tr>
                        <td style="width:20%;">
                            @Html.DisplayFor(modelItem => item.PublicEmail)
                        </td>
                        <td style="width:20%;">
                            @Html.DisplayFor(modelItem => item.ContactPersonOne)
                        </td>
                        <td style="width:20%;">
                            @Html.DisplayFor(modelItem => item.PersonalEmailOne)
                        </td>
                        <td style="width:20%;">
                            @Html.DisplayFor(modelItem => item.ContactPersonTwo)
                        </td>
                        <td style="width:20%;">
                            @Html.DisplayFor(modelItem => item.PersonalEmailTwo)
                        </td>
                    </tr>
                </table>

                <table class="table">
                    <thead>
                    <tr>
                        <th style="width:20%;">
                            @Html.DisplayNameFor(model => model.DateCreated)
                        </th>
                        <th style="width:20%;">
                            @Html.DisplayNameFor(model => model.GroupName)
                        </th>
                        <th style="width:20%;">
                            @Html.DisplayNameFor(model => model.Comments)
                        </th>
                        <th style="width:20%;">
                            @Html.DisplayNameFor(model => model.AccountManager)
                        </th>
                        <th style="width:20%;">
                            <a onclick="setCookie()" asp-controller="Dashboard" asp-action="Create">Create Task</a>
                        </th>
                    </tr>
                    </thead>
                    <tr>
                        <td style="width:20%;">
                            @Html.DisplayFor(modelItem => item.DateCreated)
                        </td>
                        <td style="width:20%;">
                            @Html.DisplayFor(modelItem => item.GroupName)
                        </td>
                        <td style="width:20%;">
                            @Html.DisplayFor(modelItem => item.Comments)
                        </td>
                        <td style="width:20%;">
                            @Html.DisplayFor(modelItem => item.AccountManager)
                        </td>
                        <td style="width:20%;">
                            <a asp-action="Edit" asp-route-id="@item.CompanyName">Edit</a> |
                            <a asp-action="Details" asp-route-id="@item.CompanyName">Details</a> |
                            <a asp-action="Delete" asp-route-id="@item.CompanyName">Delete</a>
                        </td>
                    </tr>
                </table>
            </h5>
        </div>
    </div>
}

<style>
.collapsible {
  border-radius: 10px;
  background-color: #eee;
  color: #444;
  cursor: pointer;
  padding: 18px;
  width: 50%;
  border: 0;
  text-align: left;
  outline: none;
  font-size: 15px;
}

/* Add a background color to the button if it is clicked on (add the .active class with JS), and when you move the mouse over it (hover) */
.active, .collapsible:hover {
  background-color: #ccc;
}

/* Style the collapsible content. Note: hidden by default */
.content {
  padding: 0 18px;
  display: none;
  overflow: hidden;
  background-color: transparent;
}
.collapsible:after {
  content: '\02795'; /* Unicode character for "plus" sign (+) */
  font-size: 13px;
  color: black;
  float: right;
  margin-left: 5px;
  focus: 
}

.collapsible:focus {outline:0 !important;}

.active:after {
  content: "\2796"; /* Unicode character for "minus" sign (-) */
}

}

</style>

<script>
    var coll = document.getElementsByClassName("collapsible");
    var i;

    for (i = 0; i < coll.length; i++) {
    coll[i].addEventListener("click", function() {
        this.classList.toggle("active");
        var content = this.nextElementSibling;
        if (content.style.display === "block") {
        content.style.display = "none";
        } else {
        content.style.display = "block";
        }
    });
    }
</script>

<script>
function setCookie() {
    console.log(this)
}
</script>